// AUTO-GENERATED by scripts/extract-data.mjs from
// ../spectera-pillar-feasibility-report-v4.html (200) + the 17 v3-only checks
// from "../spectera-pillar-feasibility-report 3 (3).html". Do not edit by hand.
// Re-run `node scripts/extract-data.mjs` to regenerate.

import type { BucketKey, BucketMeta, Layer } from '@/types';

export const LAYERS: Layer[] = [
  "Layer 1 — Website",
  "Layer 2 — Infrastructure",
  "Layer 3 — Content & Intelligence",
  "Layer 4 — Paid Discovery",
  "Layer 5 — Runtime Monitoring & Insights"
] as Layer[];

export const LAYER_BG: Record<Layer, string> = {
  "Layer 1 — Website": "#374151",
  "Layer 2 — Infrastructure": "#0c4a6e",
  "Layer 3 — Content & Intelligence": "#7c3aed",
  "Layer 4 — Paid Discovery": "#9a3412",
  "Layer 5 — Runtime Monitoring & Insights": "#b45309"
} as Record<Layer, string>;

// Pillars belonging to each non-default layer (Layer 1 is the fallback).
export const LAYER_PILLARS: { layer2: string[]; layer3: string[]; layer4: string[]; layer5: string[] } = {
  "layer2": [
    "SSL & Domain Health",
    "Third-Party Script Health",
    "Analytics & Tag Integrity"
  ],
  "layer3": [
    "Content Change Detection",
    "Regulatory Intelligence",
    "Audit Trail & Evidence",
    "Competitive Benchmark"
  ],
  "layer4": [
    "Deep-dive Workstreams"
  ],
  "layer5": [
    "Availability & Monitoring",
    "UX & Behaviour",
    "Observability",
    "Content Quality",
    "Visual Stability"
  ]
};

export const BUCKET_ORDER: BucketKey[] = [
  "spectera",
  "thirdparty",
  "agentic",
  "build",
  "human"
] as BucketKey[];

export const BUCKETS: Record<BucketKey, BucketMeta> = {
  "spectera": {
    "label": "Spectera now · Site Audit",
    "icon": "🟢",
    "color": "#15803d",
    "bg": "#dcfce7",
    "desc": "Live in the Site Audit crawler today — single URL, fully automated, no visual judgment"
  },
  "thirdparty": {
    "label": "3rd-party API",
    "icon": "🔵",
    "color": "#1e40af",
    "bg": "#dbeafe",
    "desc": "Plug in an external API or feed — low code"
  },
  "agentic": {
    "label": "AI (Claude Prompting)",
    "icon": "🟣",
    "color": "#5b21b6",
    "bg": "#ede9fe",
    "desc": "Claude reads the page text / structure — non-visual judgment"
  },
  "build": {
    "label": "Custom build",
    "icon": "⚙️",
    "color": "#9a3412",
    "bg": "#ffedd5",
    "desc": "URL-only Playwright plumbing: DOM / interaction / network / crawl-diff"
  },
  "human": {
    "label": "Human only",
    "icon": "👤",
    "color": "#374151",
    "bg": "#f3f4f6",
    "desc": "No URL-only tool replaces this — incl. visual-fidelity checks"
  }
} as Record<BucketKey, BucketMeta>;
