// AUTO-GENERATED by scripts/extract-data.mjs from
// ../spectera-pillar-feasibility-report-v4.html (200) + the 17 v3-only checks
// from "../spectera-pillar-feasibility-report 3 (3).html", with the "roadmap"
// field merged in from ../spectra-implementation-roadmap.html. Do not edit by
// hand. Re-run `node scripts/extract-data.mjs` to regenerate.

import type { BucketKey, BucketMeta } from '@/types';

export const BUCKET_ORDER: BucketKey[] = [
  "spectera",
  "thirdparty",
  "agentic",
  "build",
  "human"
] as BucketKey[];

export const BUCKETS: Record<BucketKey, BucketMeta> = {
  "spectera": {
    "label": "Spectera now · Site Audit",
    "icon": "🟢",
    "color": "#15803d",
    "bg": "#dcfce7",
    "desc": "Live in the Site Audit crawler today — single URL, fully automated, no visual judgment"
  },
  "thirdparty": {
    "label": "3rd-party API",
    "icon": "🔵",
    "color": "#1e40af",
    "bg": "#dbeafe",
    "desc": "Plug in an external API or feed — low code"
  },
  "agentic": {
    "label": "AI (Claude Prompting)",
    "icon": "🟣",
    "color": "#5b21b6",
    "bg": "#ede9fe",
    "desc": "Claude reads the page text / structure — non-visual judgment"
  },
  "build": {
    "label": "Custom build",
    "icon": "⚙️",
    "color": "#9a3412",
    "bg": "#ffedd5",
    "desc": "URL-only Playwright plumbing: DOM / interaction / network / crawl-diff"
  },
  "human": {
    "label": "Human only",
    "icon": "👤",
    "color": "#374151",
    "bg": "#f3f4f6",
    "desc": "No URL-only tool replaces this — incl. visual-fidelity checks"
  }
} as Record<BucketKey, BucketMeta>;
